component:
  componentReferences: []
  name: kyma-project.io/module/example-module-name
  provider: internal
  repositoryContexts:
  - baseUrl: operator-test-registry.localhost:50241
    componentNameMapping: urlPath
    type: ociRegistry
  resources:
  - access:
      digest: sha256:9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
      type: localOciBlob
    name: config
    relation: local
    type: yaml
    version: v0.0.30
  - access:
      digest: sha256:079e0eeb88187349a2dd2584bbce122b4319acb767e1c23a9c49beace26ceda0
      type: localOciBlob
    name: nginx-ingress
    relation: local
    type: helm-chart
    version: v0.0.30
  sources: []
  version: v0.0.30
meta:
  schemaVersion: v2

