component:
  componentReferences: []
  name: kyma-project.io/module/example-module-name
  provider: internal
  repositoryContexts:
  - baseUrl: operator-test-registry.localhost:50241
    componentNameMapping: urlPath
    type: ociRegistry
  resources:
  - access:
      digest: sha256:9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
      type: localOciBlob
    name: config
    relation: local
    type: yaml
    version: v0.0.35
  - access:
      digest: sha256:45f2b9d3fbba23f5de6989bf8887b6b113a2b192c6ac07cbccd418aad09c0dee
      type: localOciBlob
    name: nginx-ingress
    relation: local
    type: helm-chart
    version: v0.0.35
  sources: []
  version: v0.0.35
meta:
  schemaVersion: v2

