kind: ConfigMap
apiVersion: v1
metadata:
  name: kyma-component-manifest
  namespace: default
  labels:
    "operator.kyma-project.io/managed-by": "kyma-operator"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/release": "v1.0.2"
data:
  manifest: |-
    crd-url: ""
    kind: Manifest
    group: component.kyma-project.io
    resource: manifests
    version: v1alpha1
    spec: 
      defaultNamespace: "default"