apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: default
spec:
  release: v1.0.2
  components:
    - name: istio
    - name: serverless
    - name: manifest
      settings:
        createChart: "true"
        chartName: cert-manager
        releaseName: jet
        repoName: jetstack
        url: https://charts.jetstack.io
        clientConfig: "CreateNamespace=true,Namespace=jet-cert"