apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-override
  namespace: default
  labels:
    kyma-project.io/config-override: "example-module-name-nginx-ingress"
data:
  values.yaml: |
    fullNameOverride=ft-123