apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-override
  namespace: default
  labels:
    extension.kyma-project.io/config-override: example-module-name-nginx-ingress
    operator.kyma-project.io/override-type: helm-values
data:
  values.yaml: |
    fullNameOverride=ft-123
    testKey=testValue