apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: moduletemplate-template
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "kyma-operator"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "template"
  annotations:
    "operator.kyma-project.io/module-version": "0.0.4"
    "operator.kyma-project.io/module-provider": "internal"
    "operator.kyma-project.io/descriptor-schema-version": "v2"
spec:
  target: remote
  channel: stable
  data:
    apiVersion: component.kyma-project.io/v1alpha1
    kind: Sample
    metadata:
      name: sample-sample
    spec:
      chartPath: "./module-chart"
      releaseName: "redis-release"
      chartFlags: "Namespace=redis,CreateNamespace=true"
  descriptor:
    component:
      componentReferences: []
      name: kyma.project.io/module/template
      provider: internal
      repositoryContexts:
      - baseUrl: op-kcp-registry.localhost:54885/unsigned
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:6909531b6d461dbeed33b375075de862f354cf99e69c31ff3558724c49e5461a
          type: localOciBlob
        name: template-operator
        relation: local
        type: helm-chart
        version: 0.0.4
      - access:
          digest: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: 0.0.4
      sources: []
      version: 0.0.4
    meta:
      schemaVersion: v2
