apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: template-operator.kyma-project.io
  name: template-operator-controller-manager
  namespace: template-operator-system
