apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
images:
- name: controller
  newName: eu.gcr.io/kyma-project/lifecycle-manager
  newTag: 5ff0336a
