apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: template-operator.kyma-project.io
  name: template-operator-controller-manager
  namespace: template-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: template-operator.kyma-project.io
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: template-operator.kyma-project.io
    spec:
      containers:
      - args:
        - --leader-elect
        image: kcp-registry.localhost:61370/unsigned/operator-images/template-operator:0.0.4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 40000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: template-operator-controller-manager
      terminationGracePeriodSeconds: 10
