name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MODULE_MANAGER: kyma-project/module-manager
jobs:
  wait-for-img:
    name: "Wait for Image Build"
    runs-on: ubuntu-latest
    steps:
      - uses: autotelic/action-wait-for-status-check@v1
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Context for which we should look for the matching status
          statusName: ${{ (github.event_name == 'pull_request') && 'pull-build' || 'main-build' }}
          timeoutSeconds: 180
          intervalSeconds: 10
      - name: Exit If Failing Build Requirement
        if: steps.wait-for-build.outputs.state != 'success'
        run: |
          echo "Image build did not succeed, skipping Smoke Test!"
          exit 1

  kustomize:
    strategy:
      matrix:
        flavor: ["", "-control-plane"]
    name: "Kustomize (dry-run${{ matrix.flavor }})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: 'operator/go.mod'
          cache-dependency-path: 'operator/go.sum'
      - run: cd operator && make dry-run${{ matrix.flavor }} IMG='*:latest'
      - name: Archive Manifests
        uses: actions/upload-artifact@v3
        with:
          retention-days: 5
          name: dry-run${{ matrix.flavor }}
          path: |
            operator/dry-run/*.yaml

  cli-integration:
    needs: [wait-for-img, kustomize]
    name: "Kyma CLI Integration"
    runs-on: ubuntu-latest
    steps:
      - name: Set up k3d
        run: wget -qO - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.4.6 bash
      - name: Set up CLI
        run: |
          wget -q https://storage.googleapis.com/kyma-cli-unstable/kyma-linux
          chmod +x kyma-linux
          mv kyma-linux /usr/local/bin/kyma
      - name: Set up kustomize V4
        run: |
          wget -qO - "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          mv kustomize /usr/local/bin/

      - name: Checkout Lifecycle-Manager
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: ${{ github.repository }}
      - name: Checkout Module-Manager
        uses: actions/checkout@v3
        with:
          repository: ${{ env.MODULE_MANAGER }}
          path: ${{ env.MODULE_MANAGER }}
          ref: main

      - name: Move Repos to SRC
        run: |
          mkdir -p $(go env GOPATH)/src/github.com/{{ .github.repository }}
          mv $GITHUB_WORKSPACE/{{ .github.repository }} $(go env GOPATH)/src/github.com/{{ .github.repository }}
          mkdir -p $(go env GOPATH)/src/github.com/${{ env.MODULE_MANAGER }}
          mv $GITHUB_WORKSPACE/${{ env.MODULE_MANAGER }} $(go env GOPATH)/src/github.com/${{ env.MODULE_MANAGER }}

      - name: Override Kustomize Controller Image TAG in Pull Request to PR Image
        if: github.event_name == 'pull_request'
        run: |
          cd $(go env GOPATH)/src/github.com/{{ .github.repository }}
          cd operator/config/manager
          kustomize edit set image controller="*:PR-${{ github.event.pull_request.number }}"

      - name: Run Deploy
        run: kyma alpha deploy --source=local

  smoke:
    needs: [wait-for-img, kustomize]
    name: "Smoke"
    strategy:
      matrix:
        os: [ubuntu-latest]
        provision-type: ["kyma-cli", "kind"]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        cache: true
        go-version-file: 'tests/smoke/go.mod'
        cache-dependency-path: 'tests/smoke/go.sum'

    - name: Set up k3d/kyma for ${{ matrix.provision-type }}
      if: ${{ matrix.provision-type }} == "kyma-cli"
      run: |
        wget -qO - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.4.6 bash
        wget -q https://storage.googleapis.com/kyma-cli-unstable/kyma-linux
        chmod +x kyma-linux
        mv kyma-linux /usr/local/bin/kyma

    - name: Set up kustomize V4
      run: |
        wget -qO - "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        mv kustomize /usr/local/bin/

    - name: Override Kustomize Controller Image TAG in Pull Request to PR Image
      if: github.event_name == 'pull_request'
      run: |
        cd operator/config/manager
        kustomize edit set image controller="*:PR-${{ github.event.pull_request.number }}"

    - name: Run Smoke Tests
      run: cd tests/smoke && go test smoke_test.go -v -provision-type ${{ matrix.provision-type }}
